export enum BasemapType {
  DarkGray = "dark-gray",
  DarkGrayVector = "dark-gray-vector",
  Gray = "gray",
  GrayVector = "gray-vector",
  Hybrid = "hybrid",
  NationalGeographic = "national-geographic",
  Oceans = "oceans",
  OSM = "osm",
  Satellite = "satellite",
  Streets = "streets",
  StreetsNavigationVector = "streets-navigation-vector",
  StreetsNightVector = "streets-night-vector",
  StreetsReliefVector = "streets-relief-vector",
  StreetsVector = "streets-vector",
  Terrain = "terrain",
  Topo = "topo",
  TopoVector = "topo-vector",
}
